const sass = require('sass');

// ...existing code...

sass.compileAsync('path/to/your/file.scss', {
  // ...existing options...
}).then(result => {
  // ...handle result...
}).catch(error => {
  // ...handle error...
});

// ...existing code...
